-- SQL script to seed surveyors into the database
-- Run this in your Supabase SQL Editor

-- Function to generate avatar URL (using UI Avatars service)
-- Note: This is just for reference. The actual URLs will be generated by the app.

INSERT INTO surveyors (name, photo_url, active) VALUES
  ('Barry McDonald', 'https://ese.engsurveys.com.au/profiles/0nxyj07q65g1.jpg', true),
  ('Bradley Gosling', 'https://ese.engsurveys.com.au/profiles/p8j70vxm6w4e.jpg', true),
  ('Cameron Steer', 'https://ui-avatars.com/api/?name=Cameron+Steer&size=200&background=fbbf24&color=000000&bold=true&format=png', true),
  ('Changyi Tang', 'https://ese.engsurveys.com.au/profiles/regl9kwv9moy.jpg', true),
  ('Chen Bai', 'https://ese.engsurveys.com.au/profiles/m4pz9ey108gn.jpg', true),
  ('Daniel Corcoran', 'https://ese.engsurveys.com.au/profiles/k2v3jkp6891m.jpg', true),
  ('Dario Rigon', 'https://ese.engsurveys.com.au/profiles/zpr1840rqng2.jpg', true),
  ('Darren Cross', 'https://ese.engsurveys.com.au/profiles/x324qx18repd.jpg', true),
  ('David Topfer', 'https://ese.engsurveys.com.au/profiles/3kyw0lx0o4de.jpg', true),
  ('Ethan Spinks', 'https://ese.engsurveys.com.au/profiles/84zo6jdy6wxy.jpg', true),
  ('Justin Scott', 'https://ese.engsurveys.com.au/profiles/0nxyj0e7865g.jpg', true),
  ('Kat Bergin', 'https://ese.engsurveys.com.au/profiles/2g1l63nw9j3q.jpg', true),
  ('Luke Shawcross', 'https://ese.engsurveys.com.au/profiles/r4ne9xqx035w.jpg', true),
  ('Mark Ainsworth', 'https://ese.engsurveys.com.au/profiles/ymxoqdxj4n67.jpg', true),
  ('Matthew Gooding', 'https://ese.engsurveys.com.au/profiles/48yz9p2m6ev7.jpg', true),
  ('Michael Templer', 'https://ese.engsurveys.com.au/profiles/vxz2qemj1ge3.jpg', true),
  ('Yasar Chitthiwala', 'https://ui-avatars.com/api/?name=Yasar+Chitthiwala&size=200&background=fbbf24&color=000000&bold=true&format=png', true)
ON CONFLICT DO NOTHING;

-- Optional: Add email column if you want to store emails
-- First, add the column if it doesn't exist:
-- ALTER TABLE surveyors ADD COLUMN IF NOT EXISTS email TEXT;

-- Then update with emails:
-- UPDATE surveyors SET email = 'barry.mcdonald@engsurveys.com.au' WHERE name = 'Barry McDonald';
-- UPDATE surveyors SET email = 'bradley.gosling@engsurveys.com.au' WHERE name = 'Bradley Gosling';
-- UPDATE surveyors SET email = 'csteer@engsurveys.com.au' WHERE name = 'Cameron Steer';
-- UPDATE surveyors SET email = 'changyi.tang@engsurveys.com.au' WHERE name = 'Changyi Tang';
-- UPDATE surveyors SET email = 'chen.bai@engsurveys.com.au' WHERE name = 'Chen Bai';
-- UPDATE surveyors SET email = 'daniel.corcoran@engsurveys.com.au' WHERE name = 'Daniel Corcoran';
-- UPDATE surveyors SET email = 'dario.rigon@engsurveys.com.au' WHERE name = 'Dario Rigon';
-- UPDATE surveyors SET email = 'darren.cross@engsurveys.com.au' WHERE name = 'Darren Cross';
-- UPDATE surveyors SET email = 'david.topfer@engsurveys.com.au' WHERE name = 'David Topfer';
-- UPDATE surveyors SET email = 'ethan.spinks@engsurveys.com.au' WHERE name = 'Ethan Spinks';
-- UPDATE surveyors SET email = 'justin.scott@engsurveys.com.au' WHERE name = 'Justin Scott';
-- UPDATE surveyors SET email = 'kathryn.bergin@engsurveys.com.au' WHERE name = 'Kat Bergin';
-- UPDATE surveyors SET email = 'luke.shawcross@engsurveys.com.au' WHERE name = 'Luke Shawcross';
-- UPDATE surveyors SET email = 'mark.ainsworth@engsurveys.com.au' WHERE name = 'Mark Ainsworth';
-- UPDATE surveyors SET email = 'matthew.gooding@engsurveys.com.au' WHERE name = 'Matthew Gooding';
-- UPDATE surveyors SET email = 'michael.templer@engsurveys.com.au' WHERE name = 'Michael Templer';
-- UPDATE surveyors SET email = 'yasar.chitthiwala@engsurveys.com.au' WHERE name = 'Yasar Chitthiwala';

